CREATE TABLE IF NOT EXISTS rpt_work_plan (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL COMMENT '填写人ID',
    department_id BIGINT COMMENT '部门ID（冗余，方便查询）',
    report_date DATE NOT NULL COMMENT '报告日期',
    title VARCHAR(128) COMMENT '标题',
    content TEXT NOT NULL COMMENT '计划内容',
    status VARCHAR(16) DEFAULT 'draft' COMMENT '状态：draft/submitted/approved/rejected',
    approver_id BIGINT COMMENT '审批人ID',
    approve_comment VARCHAR(512) COMMENT '审批意见',
    approve_time DATETIME COMMENT '审批时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除：0=正常 1=已删除',
    version INT DEFAULT 0 COMMENT '乐观锁版本号',
    UNIQUE KEY uk_plan_user_date (user_id, report_date),
    INDEX idx_plan_date (report_date),
    INDEX idx_plan_dept (department_id),
    INDEX idx_plan_status (status)
) ENGINE=InnoDB COMMENT='工作计划';

CREATE TABLE IF NOT EXISTS rpt_work_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL COMMENT '填写人ID',
    department_id BIGINT COMMENT '部门ID（冗余，方便查询）',
    report_date DATE NOT NULL COMMENT '报告日期',
    title VARCHAR(128) COMMENT '标题',
    content TEXT NOT NULL COMMENT '日志内容',
    status VARCHAR(16) DEFAULT 'draft' COMMENT '状态：draft/submitted/approved/rejected',
    approver_id BIGINT COMMENT '审批人ID',
    approve_comment VARCHAR(512) COMMENT '审批意见',
    approve_time DATETIME COMMENT '审批时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除：0=正常 1=已删除',
    version INT DEFAULT 0 COMMENT '乐观锁版本号',
    UNIQUE KEY uk_log_user_date (user_id, report_date),
    INDEX idx_log_date (report_date),
    INDEX idx_log_dept (department_id),
    INDEX idx_log_status (status)
) ENGINE=InnoDB COMMENT='工作日志';
