-- V8: 客户/供应商模块建表
CREATE TABLE IF NOT EXISTS cust_customer (
    id              BIGINT        PRIMARY KEY AUTO_INCREMENT,
    customer_code   VARCHAR(64)   NOT NULL UNIQUE COMMENT '客户编码',
    customer_name   VARCHAR(256)  NOT NULL COMMENT '客户名称(中文)',
    customer_name_en VARCHAR(256) COMMENT '客户名称(英文)',
    customer_type   VARCHAR(32)   COMMENT '类型: buyer/agent/distributor',
    country         VARCHAR(64)   COMMENT '国家',
    contact_person  VARCHAR(64)   COMMENT '联系人',
    contact_email   VARCHAR(128)  COMMENT '邮箱',
    contact_phone   VARCHAR(32)   COMMENT '电话',
    contact_fax     VARCHAR(32)   COMMENT '传真',
    website         VARCHAR(256)  COMMENT '网址',
    address         TEXT          COMMENT '地址',
    credit_limit    DECIMAL(18,2) COMMENT '信用额度(USD)',
    payment_terms   VARCHAR(64)   COMMENT '付款方式',
    tax_id          VARCHAR(64)   COMMENT '税号/VAT',
    swift_code      VARCHAR(32)   COMMENT 'SWIFT Code',
    bank_name       VARCHAR(256)  COMMENT '银行名称',
    bank_account    VARCHAR(64)   COMMENT '银行账号',
    status          TINYINT       DEFAULT 1 COMMENT '1=启用 0=停用',
    created_by      BIGINT,
    updated_by      BIGINT,
    created_at      DATETIME      DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted         TINYINT       DEFAULT 0,
    INDEX idx_country (country)
) ENGINE=InnoDB COMMENT='海外客户';

CREATE TABLE IF NOT EXISTS cust_supplier (
    id              BIGINT        PRIMARY KEY AUTO_INCREMENT,
    supplier_code   VARCHAR(64)   NOT NULL UNIQUE COMMENT '供应商编码',
    supplier_name   VARCHAR(256)  NOT NULL COMMENT '供应商名称',
    province        VARCHAR(32)   COMMENT '省份',
    city            VARCHAR(64)   COMMENT '城市',
    contact_person  VARCHAR(64)   COMMENT '联系人',
    contact_phone   VARCHAR(32)   COMMENT '电话',
    contact_email   VARCHAR(128)  COMMENT '邮箱',
    address         TEXT          COMMENT '地址',
    rating          INT           DEFAULT 0 COMMENT '评分 1-5',
    payment_terms   VARCHAR(64)   COMMENT '付款方式',
    bank_name       VARCHAR(256)  COMMENT '银行名称',
    bank_account    VARCHAR(64)   COMMENT '银行账号',
    tax_id          VARCHAR(64)   COMMENT '税号',
    main_products   TEXT          COMMENT '主营产品',
    cooperation_years INT         COMMENT '合作年限',
    status          TINYINT       DEFAULT 1 COMMENT '1=启用 0=停用',
    created_by      BIGINT,
    updated_by      BIGINT,
    created_at      DATETIME      DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted         TINYINT       DEFAULT 0,
    INDEX idx_province (province)
) ENGINE=InnoDB COMMENT='国内供应商';
